DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = hello-world blink-hello timer-test sensors-demo

HAVE_BANKING=1

all: $(CONTIKI_PROJECT) 

CONTIKI = ../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
