DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI = ../../../..

HAVE_BANKING=1

all: example-mote example-dongle example-abc example-motor

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
